// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller"
application.register("autohide", AutohideController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)